[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/mj.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/arriere-salle.html"
  [headers.values]
    X-Robots-Tag = "noindex"
